[package]
name = "uji-ui"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
base64 = "0.22"
arboard = { version = "3", default-features = false, features = ["wayland-data-control"] }
nucleo-matcher = "0.3"
uji-agent = { path = "../agent" }
ratatui = "0.30"
crossterm = "0.29"
serde_json = "1"
pulldown-cmark = { version = "0.13.4", default-features = false }
chrono-humanize = "0.2.3"
chrono = { version = "0.4.45", default-features = false }
strum = { version = "0.28.0", features = ["derive"] }

[lints]
workspace = true
