[package]
name = "libuji"
version.workspace = true
edition.workspace = true

[dependencies]
uji-core = { path = "../core" }
tui = { path = "../tui" }
clap = { version = "4", features = ["derive"] }
mlua = { version = "0.12", features = ["lua54", "vendored"] }

[[bin]]
name = "uji"
path = "src/bin/cli.rs"

[lints]
workspace = true
